// Movement Theater Phase 3, Stage A — external activation data.
//
// Before this module, activation lived inside `actions.js` as JavaScript
// callbacks (`activations: (t) => ({...})`, `bump(t, a, b, peak)`), which meant:
//   * a muscle's activation was code, not data — an SME could not edit it,
//   * every frame allocated a fresh object of ~54 keys (audit A5 class),
//   * roles were re-derived per muscle per action from peak thresholds, so the
//     hand-curated roles and the derived ones could silently disagree.
//
// Now the curves live in `content/kinesiology/clips/<clipId>.json`, generated by
// `scripts/bake-activation-data.mjs` and validated on every `npm run verify`.
// This module is the runtime: it decodes a document once and answers
// `levelsAt(t)` from a reused buffer, so the per-frame path allocates nothing.
//
// The three-level disclaimer contract (Masterplan §4.3) is implemented in the
// UI; the provenance that feeds it travels in the document (`evidence`).

/** Canonical muscle order. Matches `MUSCLES` in performanceRig.js, sides expanded. */
export const ACTIVATION_ORDER = (() => {
  // Kept as a literal list (not derived from the rig) so a rig edit cannot
  // silently reorder the activation texture rows: the smoke test asserts the two
  // agree instead.
  const base = [
    ['gluteusMaximus', true], ['gluteusMedius', true], ['rectusFemoris', true],
    ['quadriceps', true], ['hamstrings', true], ['iliopsoas', true],
    ['gastrocnemius', true], ['tibialisAnterior', true], ['soleus', true],
    ['rectusAbdominis', false], ['erectorSpinae', false], ['obliquusExternus', true],
    ['latissimusDorsi', true], ['serratusAnterior', true], ['upperTrapezius', true],
    ['deltoid', true], ['bicepsBrachii', true], ['tricepsBrachii', true],
    ['forearmFlexors', true], ['forearmExtensors', true], ['pronatorTeres', true],
    ['adductorPollicis', true], ['supraspinatus', true], ['masseter', true],
    ['lateralPterygoid', true], ['temporalis', true], ['digastric', false],
    ['orbicularisOris', false], ['buccinator', true]
  ];
  const out = [];
  for (const [id, side] of base) {
    if (side) { out.push(`${id}.L`, `${id}.R`); } else { out.push(id); }
  }
  return out;
})();

/** Muscle id -> row index in ACTIVATION_ORDER. Built once; the per-frame paths
 *  use it instead of scanning the array. */
export const ACTIVATION_INDEX = new Map(ACTIVATION_ORDER.map((id, i) => [id, i]));

/** Role codes packed into the activation texture (G channel). 0 = absent. */
export const ROLE_CODES = { PM: 1, SY: 2, AN: 3, ST: 4, IN: 5 };
/** Contraction codes packed into the activation texture (B channel). 0 = unknown. */
export const CONTRACTION_CODES = { concentric: 1, eccentric: 2, isometric: 3, mixed: 4 };

/**
 * Peak thresholds for the derived-role fallback. Unchanged from the Phase 1
 * curation pass (Masterplan §4.3): PM ≥ 0.70, SY ≥ 0.38, ST ≥ 0.15, else IN.
 * Curated roles in the data always win; this only fills gaps.
 */
export const ROLE_PEAK_AGONIST = 0.70;
export const ROLE_PEAK_SYNERGIST = 0.38;
export const ROLE_PEAK_STABILIZER = 0.15;
/** Below this peak a muscle is inactive regardless of thresholds (taxonomy floor). */
export const ACTIVATION_FLOOR = 0.05;

export function deriveRole(peak) {
  if (peak < ACTIVATION_FLOOR) return 'IN';
  if (peak >= ROLE_PEAK_AGONIST) return 'PM';
  if (peak >= ROLE_PEAK_SYNERGIST) return 'SY';
  if (peak >= ROLE_PEAK_STABILIZER) return 'ST';
  return 'IN';
}

/**
 * Fritsch–Carlson monotone cubic Hermite interpolation.
 *
 * Why not linear: the authored bumps are raised cosines and the mocap curves are
 * muscle timing envelopes; linear interpolation of a 6-key envelope puts visible
 * corners in the colour animation. Why not a plain cubic spline: Catmull-Rom
 * overshoots, and an overshoot above 1.0 is an invalid activation (audit A11
 * already found 1.3 in the data once).
 *
 * @param {number[]} xs strictly increasing, xs[0] = 0, xs[n-1] = 1
 * @param {number[]} ys values in [0, 1]
 */
function makeMonotoneCubic(xs, ys) {
  const n = xs.length;
  if (n === 1) { const v = ys[0]; return () => v; }
  const dx = new Array(n - 1);
  const slope = new Array(n - 1);
  for (let i = 0; i < n - 1; i++) {
    dx[i] = xs[i + 1] - xs[i];
    slope[i] = (ys[i + 1] - ys[i]) / dx[i];
  }
  const m = new Array(n);
  m[0] = slope[0];
  m[n - 1] = slope[n - 2];
  for (let i = 1; i < n - 1; i++) {
    if (slope[i - 1] * slope[i] <= 0) { m[i] = 0; } else {
      const w1 = 2 * dx[i] + dx[i - 1];
      const w2 = dx[i] + 2 * dx[i - 1];
      m[i] = (w1 + w2) / (w1 / slope[i - 1] + w2 / slope[i]);
    }
  }
  const clamp = (i, s) => {
    if (slope[i] === 0) return 0;
    const s3 = 3 * slope[i];
    return Math.abs(s) > Math.abs(s3) ? s3 : s;
  };
  for (let i = 0; i < n - 1; i++) {
    if (slope[i] === 0) { m[i] = 0; m[i + 1] = 0; }
    else { m[i] = clamp(i, m[i]); m[i + 1] = clamp(i, m[i + 1]); }
  }
  return (x) => {
    if (x <= xs[0]) return ys[0];
    if (x >= xs[n - 1]) return ys[n - 1];
    let lo = 0;
    let hi = n - 1;
    while (hi - lo > 1) {
      const mid = (lo + hi) >> 1;
      if (xs[mid] <= x) lo = mid; else hi = mid;
    }
    const h = dx[lo];
    const t = (x - xs[lo]) / h;
    const t2 = t * t;
    const t3 = t2 * t;
    const h00 = 2 * t3 - 3 * t2 + 1;
    const h10 = t3 - 2 * t2 + t;
    const h01 = -2 * t3 + 3 * t2;
    const h11 = t3 - t2;
    return h00 * ys[lo] + h10 * h * m[lo] + h01 * ys[lo + 1] + h11 * h * m[lo + 1];
  };
}

const ROLE_ENUM = new Set(Object.keys(ROLE_CODES));
const CONTRACTION_ENUM = new Set(Object.keys(CONTRACTION_CODES));

/**
 * Validate one activation document. Returns a list of human-readable problems
 * (empty = valid). Used by the bake step and by `verify:kine-activation`, so a
 * hand-edited document fails the build rather than the renderer.
 *
 * @param {object} doc
 * @param {{ knownIds?: Set<string>, expected?: { fps?: number, frameCount?: number, durationS?: number } }} [opts]
 */
export function validateActivationDoc(doc, opts = {}) {
  const problems = [];
  const p = (msg) => problems.push(msg);
  if (!doc || typeof doc !== 'object') return ['document is not an object'];
  if (typeof doc.clipId !== 'string' || !doc.clipId) p('clipId must be a non-empty string');
  if (typeof doc.label !== 'string' || !doc.label) p('label must be a non-empty string');
  if (!doc.source || typeof doc.source.kind !== 'string') p('source.kind is required');
  if (!['mocap', 'authored'].includes(doc.source?.kind)) p(`source.kind "${doc.source?.kind}" must be mocap or authored`);
  if (!doc.source?.citation) p('source.citation is mandatory (every number needs a citable basis)');
  for (const field of ['fps', 'frameCount', 'durationS']) {
    if (typeof doc[field] !== 'number' || !(doc[field] > 0)) p(`${field} must be a positive number`);
  }
  if (opts.expected) {
    // Tolerance: durationS is stored rounded to 1e-5 so the JSON stays readable,
    // which is well inside the 1/1000 of a frame that the 30 fps grid allows.
    for (const [field, want] of Object.entries(opts.expected)) {
      if (want == null) continue;
      if (Math.abs((doc[field] ?? NaN) - want) > 1e-4) p(`${field} is ${doc[field]}, declared duration implies ${want}`);
    }
  }
  if (!Array.isArray(doc.muscles) || doc.muscles.length === 0) { p('muscles[] must be a non-empty array'); return problems; }
  const seen = new Set();
  doc.muscles.forEach((m, i) => {
    const at = `muscles[${i}]${m && m.muscleId ? ` (${m.muscleId})` : ''}`;
    if (typeof m?.muscleId !== 'string' || !m.muscleId) { p(`${at}: muscleId is required`); return; }
    if (opts.knownIds && !opts.knownIds.has(m.muscleId)) p(`${at}: unknown muscleId`);
    if (seen.has(m.muscleId)) p(`${at}: duplicate muscleId`);
    seen.add(m.muscleId);
    if (!ROLE_ENUM.has(m.role)) p(`${at}: role "${m.role}" is not one of ${[...ROLE_ENUM].join('/')}`);
    if (!CONTRACTION_ENUM.has(m.contraction)) p(`${at}: contraction "${m.contraction}" is not one of ${[...CONTRACTION_ENUM].join('/')}`);
    if (!Array.isArray(m.activation) || m.activation.length < 2) p(`${at}: activation needs at least 2 keyframes`);
    else if (m.activation.length > 64) p(`${at}: ${m.activation.length} keyframes exceeds the 64-key ceiling (12 is the budget; more is allowed only with a recorded quality.maxError — see bake-activation-data.mjs)`);
    else if (m.activation.length > 12 && !(m.quality && typeof m.quality.maxError === 'number')) p(`${at}: ${m.activation.length} keyframes needs the extended key budget, which must record quality.maxError`);
    else {
      let prev = -Infinity;
      for (const [k, pair] of m.activation.entries()) {
        if (!Array.isArray(pair) || pair.length !== 2) { p(`${at}: keyframe ${k} must be [t, value]`); continue; }
        const [t, v] = pair;
        if (!(t > prev)) p(`${at}: keyframe ${k} t=${t} is not strictly increasing`);
        prev = t;
        if (!(t >= 0 && t <= 1)) p(`${at}: keyframe ${k} t=${t} is outside [0, 1]`);
        if (!(v >= 0 && v <= 1)) p(`${at}: keyframe ${k} value ${v} is outside [0, 1] (audit A11)`);
      }
      if (m.activation[0][0] !== 0) p(`${at}: first keyframe must be t=0`);
      if (m.activation[m.activation.length - 1][0] !== 1) p(`${at}: last keyframe must be t=1`);
    }
    if (m.interpolation !== 'monotoneCubic') p(`${at}: interpolation must be monotoneCubic`);
    if (m.quality && !(m.quality.maxError <= 0.05)) p(`${at}: recorded reconstruction error ${m.quality.maxError} exceeds the 0.05 tolerance`);
    if (!m.evidence || typeof m.evidence.basis !== 'string') p(`${at}: evidence.basis is required`);
    if (!m.evidence?.citation) p(`${at}: evidence.citation is required`);
    if (m.contractionKeys) {
      if (!Array.isArray(m.contractionKeys)) p(`${at}: contractionKeys must be an array`);
      else {
        let prev = -Infinity;
        for (const [k, pair] of m.contractionKeys.entries()) {
          if (!Array.isArray(pair) || pair.length !== 2) { p(`${at}: contractionKeys[${k}] must be [t, mode]`); continue; }
          if (!(pair[0] > prev)) p(`${at}: contractionKeys[${k}] t=${pair[0]} is not increasing`);
          prev = pair[0];
          if (!CONTRACTION_ENUM.has(pair[1])) p(`${at}: contractionKeys[${k}] mode "${pair[1]}" is invalid`);
        }
      }
    }
  });
  return problems;
}

/**
 * Decode a validated activation document into a runtime curve.
 *
 * @param {object} doc
 * @param {{ order?: string[], knownIds?: Set<string>, skipValidation?: boolean }} [opts]
 */
export function decodeActivation(doc, opts = {}) {
  const order = opts.order || ACTIVATION_ORDER;
  if (!opts.skipValidation) {
    const problems = validateActivationDoc(doc, { knownIds: opts.knownIds });
    if (problems.length) throw new Error(`activation doc "${doc?.clipId}": ${problems[0]}`);
  }
  const index = new Map(order.map((id, i) => [id, i]));
  const fns = [];
  const roles = new Uint8Array(order.length);
  const contractions = new Uint8Array(order.length);
  const peaks = new Float32Array(order.length);
  const means = new Float32Array(order.length);
  const records = [];
  const byId = new Map();
  for (const m of doc.muscles) {
    const i = index.get(m.muscleId);
    if (i === undefined) continue; // not on this rig: validator warns, runtime skips
    const xs = m.activation.map((k) => k[0]);
    const ys = m.activation.map((k) => k[1]);
    fns[i] = makeMonotoneCubic(xs, ys);
    roles[i] = ROLE_CODES[m.role] || 0;
    contractions[i] = CONTRACTION_CODES[m.contraction] || 0;
    let peak = 0;
    let sum = 0;
    for (const v of ys) { peak = Math.max(peak, v); sum += v; }
    peaks[i] = peak;
    means[i] = sum / ys.length;
    const record = {
      muscleId: m.muscleId,
      role: m.role,
      contraction: m.contraction,
      contractionKeys: m.contractionKeys || null,
      peak,
      mean: means[i],
      evidence: m.evidence
    };
    records.push(record);
    byId.set(m.muscleId, record);
  }

  // Reused output buffer: the per-frame path must not allocate.
  const levels = new Float32Array(order.length);
  const packBuf = new Uint8Array(4 * order.length);
  const contractionCache = new Map();

  const contractionAt = (id, tNorm) => {
    const rec = byId.get(id);
    if (!rec) return 'inactive';
    if (!rec.contractionKeys || rec.contractionKeys.length === 0) return rec.contraction;
    // Small linear scan: <= 12 keys, no per-frame allocation.
    let mode = rec.contractionKeys[0][1];
    for (const [t, m] of rec.contractionKeys) { if (t <= tNorm) mode = m; else break; }
    return mode;
  };

  return {
    clipId: doc.clipId,
    label: doc.label,
    source: doc.source,
    fps: doc.fps,
    frameCount: doc.frameCount,
    durationS: doc.durationS,
    order,
    muscles: records,
    roles,
    contractions,
    peaks,
    means,

    /** Curated role letter for a muscle id ('PM' | 'SY' | 'AN' | 'ST' | 'IN' | null). */
    roleOf(id) {
      const i = index.get(id);
      if (i === undefined || !roles[i]) return null;
      return Object.keys(ROLE_CODES).find((k) => ROLE_CODES[k] === roles[i]) || null;
    },
    /** Falls back to the derived role so no legend row is ever blank. */
    roleFor(id) {
      const curated = this.roleOf(id);
      if (curated) return curated;
      const i = index.get(id);
      return deriveRole(i === undefined ? 0 : peaks[i]);
    },
    contractionOf(id) { return byId.get(id)?.contraction || null; },
    contractionAt,
    evidenceFor(id) { return byId.get(id)?.evidence || null; },
    peakFor(id) { const i = index.get(id); return i === undefined ? 0 : peaks[i]; },
    meanFor(id) { const i = index.get(id); return i === undefined ? 0 : means[i]; },

    /**
     * Activation for every rig muscle at normalised time t, as a REUSED
     * Float32Array. Copy it if you need to keep it; write it to the DOM or a
     * texture before the next call.
     */
    levelsAt(tNorm) {
      const t = tNorm <= 0 ? 0 : (tNorm >= 1 ? 1 : tNorm);
      for (let i = 0; i < levels.length; i++) levels[i] = fns[i] ? fns[i](t) : 0;
      return levels;
    },

    /** One-shot matrix of `count` samples — for sparklines and precomputes. */
    sample(count) {
      const out = new Float32Array(count * order.length);
      for (let s = 0; s < count; s++) {
        const t = count === 1 ? 0 : s / (count - 1);
        const row = this.levelsAt(t);
        out.set(row, s * order.length);
      }
      return out;
    },

    /**
     * Pack one data tick for the GPU path (Masterplan §4.3): one row per muscle,
     * R = activation × 255, G = role code, B = contraction code, A = flags.
     * Reused buffer; upload size is 4 × muscleCount bytes (54 muscles = 216 B,
     * inside the 512 B/tick budget).
     */
    pack(tNorm, out = packBuf) {
      const t = tNorm <= 0 ? 0 : (tNorm >= 1 ? 1 : tNorm);
      for (let i = 0; i < order.length; i++) {
        const v = fns[i] ? fns[i](t) : 0;
        const v4 = i * 4;
        out[v4] = Math.round(Math.max(0, Math.min(1, v)) * 255);
        out[v4 + 1] = roles[i];
        out[v4 + 2] = contractions[i];
        out[v4 + 3] = v < ACTIVATION_FLOOR ? 1 : 0; // flag byte: below the inactive floor
      }
      return out;
    },
    /** Bytes per data tick (`pack` output size) — asserted against the budget. */
    get packBytes() { return 4 * order.length; },
    /** Sample one muscle's curve without touching the shared buffer. */
    valueAt(id, tNorm) {
      const i = index.get(id);
      if (i === undefined || !fns[i]) return 0;
      const t = tNorm <= 0 ? 0 : (tNorm >= 1 ? 1 : tNorm);
      return fns[i](t);
    },
    /** Number of distinct contraction modes over the clip (for the legend). */
    contractionSet(id) {
      const rec = byId.get(id);
      if (!rec) return [];
      if (!rec.contractionKeys) return [rec.contraction];
      if (!contractionCache.has(id)) contractionCache.set(id, [...new Set(rec.contractionKeys.map((k) => k[1]))]);
      return contractionCache.get(id);
    }
  };
}

/**
 * Decode a map of documents, keyed by clip id.
 * @param {Record<string, object>} docs
 */
export function decodeActivationMap(docs, opts = {}) {
  return Object.fromEntries(Object.entries(docs).map(([key, doc]) => [key, decodeActivation(doc, opts)]));
}
