// Phase 2 (Masterplan §6): baked motion tracks.
//
// WHY THIS EXISTS — measured, not assumed. Loading the two CMU clips at theater
// start cost ~50 ms of the ~104 ms pre-WebGL stage on a desktop CPU (worse on a
// mid-tier phone), and the profile was NOT what the plan assumed:
//
//   parseBVH                walk 3.1 ms + jump 1.4 ms
//   computeCalibration            0.5 + 0.1
//   finalizeGround               16.1 + 8.4   <-- 60 full-scene updateMatrixWorld sweeps
//   computeStanceData x2          9.1 + 4.4   <-- 2 x frames more sweeps
//   gait + angle sweeps           ~5           <-- ~180 more sweeps
//
// Parsing was ~6 % of it. The cost was the *sweeps*: every stage re-applied the
// BVH frame and walked the whole rig (80 meshes) to read one bone's world
// position. So the fix is not "parse a smaller BVH" but "never sweep".
//
// The asset is a derived, committed file (`src/data/kinesiology/clips/*.json`,
// generated by `scripts/bake-motion-assets.mjs`, checked by `verify:motion-assets`):
//
//   * local bone rotations for every mapped rig bone, per frame, int16-quantised
//     (angular error < 0.01 deg — 100x inside the ±1 deg acceptance criterion);
//   * the raw BVH root position per frame (float32, exact);
//   * the BVH-derived calibration scale + heading yaw.
//
// Two quantities are deliberately NOT baked, because they depend on the *rig*
// (which Phase 2 replaces with the skinned figure) and are cheap to derive with a
// targeted forward-kinematic chain walk instead of a scene sweep:
//
//   * the ground offset (`groundOffsetForRig`)
//   * stance windows + plant targets (`stanceForRig`)
//
// Everything else (angles, gait stats) is derived from the baked quaternions with
// a handful of quaternion multiplications and no scene graph at all.
//
// SEMANTICS ARE NOT REIMPLEMENTED. The baker runs the shipped `applyBVHFrame` and
// records what it produced, so the baked pose is comparable with the old path for
// every frame; `verify:kine-timeline` asserts both the pose and the derived
// angles against the live BVH pipeline.

import { rigNameFor, readRootPosition, CONTACT_SPEED_MS } from './retarget.js';

export const MOTION_TRACK_VERSION = 1;
export const QUAT_SCALE = 32767;

// ---- base64 <-> typed arrays (browser + node) -------------------------------

function b64ToBytes(b64) {
  const bin = typeof atob === 'function' ? atob(b64) : Buffer.from(b64, 'base64').toString('binary');
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function bytesToB64(bytes) {
  let bin = '';
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return typeof btoa === 'function' ? btoa(bin) : Buffer.from(bin, 'binary').toString('base64');
}

export function encodeInt16(values) {
  const arr = values instanceof Int16Array ? values : Int16Array.from(values);
  return bytesToB64(new Uint8Array(arr.buffer, arr.byteOffset, arr.byteLength));
}

export function encodeFloat32(values) {
  const arr = values instanceof Float32Array ? values : Float32Array.from(values);
  return bytesToB64(new Uint8Array(arr.buffer, arr.byteOffset, arr.byteLength));
}

function decodeInt16(b64) {
  const bytes = b64ToBytes(b64);
  return new Int16Array(bytes.buffer, 0, bytes.length / 2);
}

function decodeFloat32(b64) {
  const bytes = b64ToBytes(b64);
  return new Float32Array(bytes.buffer, 0, bytes.length / 4);
}

// ---- decode -----------------------------------------------------------------

/**
 * Turn a baked document into the runtime shape the theater uses.
 *
 * @returns {{clip:string, fps:number, frameTime:number, frames:number,
 *            duration:number, bones:string[], boneIndex:Object<string,number>,
 *            quats:Int16Array, rootPos:Float32Array, scale:number, yaw:number,
 *            sourceSha256:string|null, payloadBytes:number}}
 */
export function decodeClipTracks(doc) {
  const bones = [...doc.bones];
  const quats = decodeInt16(doc.quats);
  const rootPos = decodeFloat32(doc.rootPos);
  const expected = doc.frames * bones.length * 4;
  if (quats.length !== expected) {
    throw new Error(`motion tracks ${doc.clip}: ${quats.length} quaternion components, expected ${expected}`);
  }
  if (rootPos.length !== doc.frames * 3) {
    throw new Error(`motion tracks ${doc.clip}: ${rootPos.length} root components, expected ${doc.frames * 3}`);
  }
  const boneIndex = {};
  bones.forEach((name, i) => { boneIndex[name] = i; });
  return {
    version: doc.version,
    clip: doc.clip,
    source: doc.source,
    sourceSha256: doc.sourceSha256 || null,
    fps: doc.fps,
    frameTime: doc.frameTime,
    frames: doc.frames,
    duration: doc.frames * doc.frameTime,
    bones,
    boneIndex,
    quats,
    rootPos,
    scale: doc.scale,
    yaw: doc.yaw,
    payloadBytes: (doc.quats.length + doc.rootPos.length) * 3 / 4, // base64 -> raw bytes
    provenance: doc.provenance || null
  };
}

export function decodeClipTracksMap(docs) {
  return Object.fromEntries(Object.entries(docs).map(([key, doc]) => [key, decodeClipTracks(doc)]));
}

// ---- scratch ----------------------------------------------------------------
// One scratch set per session: every function below is called from the same
// single-threaded tick, so reusing buffers keeps the render loop allocation-free.
let S = null;
function scratch(THREE) {
  if (!S) {
    S = {
      root: new THREE.Quaternion(),
      thigh: new THREE.Quaternion(),
      shank: new THREE.Quaternion(),
      foot: new THREE.Quaternion(),
      parentQ: new THREE.Quaternion(),
      invRoot: new THREE.Quaternion(),
      v1: new THREE.Vector3(),
      v2: new THREE.Vector3(),
      v3: new THREE.Vector3(),
      v4: new THREE.Vector3(),
      v5: new THREE.Vector3(),
      v6: new THREE.Vector3(),
      v7: new THREE.Vector3(),
      v8: new THREE.Vector3()
    };
  }
  return S;
}

// ---- pose application -------------------------------------------------------

/**
 * Write one baked frame onto the rig. Mirrors `applyBVHFrame` exactly: mapped
 * bones get their local quaternion, the root bone gets the scaled and
 * heading-rotated translation, and every other bone keeps whatever the caller
 * set (the theater resets them to identity first).
 */
export function applyTrackFrame(THREE, rig, tracks, frame, opts = {}) {
  const treadmill = opts.treadmill !== false;
  const yOffset = opts.yOffset || 0;
  const f = Math.max(0, Math.min(tracks.frames - 1, Math.floor(frame)));
  const { bones, quats, rootPos } = tracks;
  for (let b = 0; b < bones.length; b++) {
    const bone = rig.bones[bones[b]];
    if (!bone) continue;
    const o = (f * bones.length + b) * 4;
    bone.quaternion.set(
      quats[o] / QUAT_SCALE,
      quats[o + 1] / QUAT_SCALE,
      quats[o + 2] / QUAT_SCALE,
      quats[o + 3] / QUAT_SCALE
    ).normalize();
  }
  const p = f * 3;
  const cos = Math.cos(tracks.yaw), sin = Math.sin(tracks.yaw);
  const x = rootPos[p] * tracks.scale;
  const z = rootPos[p + 2] * tracks.scale;
  rig.bones.root.position.set(
    treadmill ? 0 : x * cos - z * sin,
    rootPos[p + 1] * tracks.scale + yOffset,
    treadmill ? 0 : x * sin + z * cos
  );
}

/** Local quaternion of one baked bone at one frame (unit length). */
export function trackBoneQuat(THREE, tracks, frame, boneName, out) {
  const q = out || new THREE.Quaternion();
  const b = tracks.boneIndex[boneName];
  if (b === undefined) return q.identity();
  const f = Math.max(0, Math.min(tracks.frames - 1, Math.floor(frame)));
  const o = (f * tracks.bones.length + b) * 4;
  const { quats } = tracks;
  return q.set(
    quats[o] / QUAT_SCALE,
    quats[o + 1] / QUAT_SCALE,
    quats[o + 2] / QUAT_SCALE,
    quats[o + 3] / QUAT_SCALE
  ).normalize();
}

function signedDeg(a, b) {
  const cross = b.y * a.z - b.z * a.y;
  const dot = a.y * b.y + a.z * b.z;
  return (Math.atan2(cross, dot) * 180) / Math.PI;
}

/**
 * Sagittal angles straight from the baked quaternions — no rig, no scene graph,
 * no `updateMatrixWorld`. Faithful to `sampleSagittalAngles` (which stays as the
 * reference implementation the tests compare against): same convention (hip
 * flexion positive, knee flexion positive, ankle dorsiflexion positive), same
 * flattening into the root's sagittal plane, same clip-frame-0 offset.
 */
export function trackRawAngles(THREE, tracks, frame, offset = null) {
  const s = scratch(THREE);
  trackBoneQuat(THREE, tracks, frame, 'root', s.root);
  trackBoneQuat(THREE, tracks, frame, 'leftUpLeg', s.thigh).premultiply(s.root);
  trackBoneQuat(THREE, tracks, frame, 'leftLeg', s.shank).premultiply(s.thigh);
  trackBoneQuat(THREE, tracks, frame, 'leftFoot', s.foot).premultiply(s.shank);

  const invRoot = s.invRoot.copy(s.root).invert();
  // Flatten each bone direction into the root's sagittal plane, exactly as the
  // reference `sag()` does: rotate into the root frame, drop x, normalise.
  // The trunk direction is (0,-1,0) rotated by the root and then back out of it,
  // which is (0,-1,0) again — `sag()` makes the trunk reference constant, and
  // reproducing that literal behaviour is the point.
  const flat = (q, out) => {
    out.set(0, -1, 0).applyQuaternion(q).applyQuaternion(invRoot);
    out.x = 0;
    return out.normalize();
  };
  const aThigh = flat(s.thigh, s.v6);
  const aShank = flat(s.shank, s.v7);
  const aFoot = flat(s.foot, s.v8);
  const aTrunk = s.v4.set(0, -1, 0);
  const raw = {
    hip: -signedDeg(aThigh, aTrunk),
    knee: Math.abs(signedDeg(aShank, aThigh)),
    ankle: -signedDeg(aFoot, aShank)
  };
  if (!offset) return raw;
  return { hip: raw.hip - offset.hip, knee: raw.knee - offset.knee, ankle: raw.ankle - offset.ankle };
}

/** Clip-frame-0 calibration offsets, i.e. `calibrateAngles(..., [0])`. */
export function zeroOffsetForClip(THREE, tracks) {
  const raw = trackRawAngles(THREE, tracks, 0, null);
  return { hip: raw.hip, knee: raw.knee, ankle: raw.ankle };
}

/** Sagittal angles with the clip's own frame 0 as zero. */
export function trackAngles(THREE, tracks, frame, offset) {
  return trackRawAngles(THREE, tracks, frame, offset);
}

// ---- fast forward kinematics (rig-aware, no scene sweep) --------------------

const _chainCache = new WeakMap();

function chainFor(rig, boneName) {
  let perRig = _chainCache.get(rig);
  if (!perRig) { perRig = {}; _chainCache.set(rig, perRig); }
  if (perRig[boneName]) return perRig[boneName];
  // Walk parents until the root bone; the root bone's own position is the
  // animated one, so it is not part of the rest-offset accumulation.
  const chain = [];
  let node = rig.bones[boneName];
  while (node && node !== rig.bones.root) {
    chain.unshift(node);
    node = node.parent;
  }
  perRig[boneName] = chain;
  return chain;
}

/**
 * World position of a bone from the baked tracks without touching the scene
 * graph: `p_child = p_parent + worldQuat(parent) * childRestOffset`, which is
 * what `getWorldPosition` returns after `updateMatrixWorld`. `opts.treadmill`
 * mirrors `applyBVHFrame` (in-place locomotion, root x/z dropped) and defaults
 * the same way, so derived measurements match the rendered pose.
 */
export function trackWorldPosition(THREE, rig, tracks, frame, boneName, opts = {}, out = null) {
  const s = scratch(THREE);
  const pos = out || s.v1;
  const treadmill = opts.treadmill !== false;
  const yOffset = opts.yOffset || 0;
  const f = Math.max(0, Math.min(tracks.frames - 1, Math.floor(frame)));
  trackBoneQuat(THREE, tracks, frame, 'root', s.parentQ);
  const p = f * 3;
  pos.set(
    treadmill ? 0 : tracks.rootPos[p] * tracks.scale,
    tracks.rootPos[p + 1] * tracks.scale + yOffset,
    treadmill ? 0 : tracks.rootPos[p + 2] * tracks.scale
  );
  for (const bone of chainFor(rig, boneName)) {
    pos.add(s.v2.copy(bone.position).applyQuaternion(s.parentQ));
    s.parentQ.multiply(trackBoneQuat(THREE, tracks, frame, bone.name, s.root));
  }
  return pos;
}

// ---- rig-dependent derivations (once per clip + rig) ------------------------

/**
 * Ground offset for the CURRENT rig — the equivalent of the old
 * `finalizeGround`, which re-posed and re-walked the whole scene for every
 * sample. This walks four bones per sample and needs no meshes.
 */
export function groundOffsetForRig(THREE, rig, tracks) {
  const step = Math.max(1, Math.floor(tracks.frames / 60));
  const pos = scratch(THREE).v3;
  let minY = Infinity;
  for (let f = 0; f < tracks.frames; f += step) {
    for (const side of ['left', 'right']) {
      trackWorldPosition(THREE, rig, tracks, f, `${side}Foot`, { yOffset: 0 }, pos);
      if (pos.y < minY) minY = pos.y;
    }
  }
  return 0.02 - minY;
}

/**
 * Stance windows + plant targets per side on the current rig. Same rule the
 * shipped `computeStanceData` applies (the foot is planted when it is not moving
 * over the ground in the capture frame, one-frame gaps filled, runs shorter than
 * six frames dropped), so the contact snap points and the honesty panel keep
 * their meaning and the two implementations cannot drift.
 */
export function stanceForRig(THREE, rig, tracks, yOffset) {
  const s = scratch(THREE);
  const shin = (() => {
    const foot = rig.bones.leftFoot;
    return foot && foot.position ? Math.hypot(foot.position.x, foot.position.y, foot.position.z) : 0.44;
  })();
  const out = {};
  for (const side of ['left', 'right']) {
    const footPos = [];
    const ankles = [];
    const p = new THREE.Vector3();
    const a = new THREE.Vector3();
    for (let f = 0; f < tracks.frames; f++) {
      // Capture frame (the planted foot is the one standing still), same rule the
      // shipped `computeStanceData` applies — pinned by verify:kine-timeline.
      trackWorldPosition(THREE, rig, tracks, f, `${side}Foot`, { yOffset, treadmill: false }, p);
      footPos.push(p.clone());
      trackWorldPosition(THREE, rig, tracks, f, `${side}Leg`, { yOffset, treadmill: false }, a);
      // The reference implementation offsets the knee by the *local* shin
      // direction; keep that literal behaviour so the windows are identical.
      trackBoneQuat(THREE, tracks, f, `${side}Leg`, s.parentQ);
      ankles.push(a.clone().add(new THREE.Vector3(0, -shin, 0).applyQuaternion(s.parentQ)));
    }
    const speed = footPos.map((q, i) => (i ? Math.hypot(q.x - footPos[i - 1].x, q.z - footPos[i - 1].z) / tracks.frameTime : 0));
    const stance = speed.map((v, i) => (i > 0 && v < CONTACT_SPEED_MS));
    for (let i = 1; i < stance.length - 1; i++) if (stance[i - 1] && stance[i + 1]) stance[i] = true;
    const windows = [];
    let start = -1;
    for (let i = 0; i <= stance.length; i++) {
      if (i < stance.length && stance[i] && start < 0) start = i;
      if ((i === stance.length || !stance[i]) && start >= 0) {
        if (i - start >= 6) windows.push({ start, end: i - 1, target: ankles[start].clone() });
        start = -1;
      }
    }
    out[side] = { windows };
  }
  return out;
}

/** Gait honesty stats (speed, cadence, step length, stance asymmetry), rig-free. */
export function gaitStatsFromTracks(tracks, stance) {
  const seconds = tracks.frames * tracks.frameTime;
  let travel = 0;
  let prev = null;
  for (let f = 0; f < tracks.frames; f += 2) {
    const p = f * 3;
    const x = tracks.rootPos[p] * tracks.scale;
    const z = tracks.rootPos[p + 2] * tracks.scale;
    if (prev) travel += Math.hypot(x - prev.x, z - prev.z);
    prev = { x, z };
  }
  const windows = [...stance.left.windows, ...stance.right.windows].sort((a, b) => a.start - b.start);
  const cadence = Math.round((windows.length / seconds) * 60);
  const step = windows.length > 0 ? travel / windows.length : 0;
  const mean = (w) => (w.length ? w.reduce((a, x) => a + (x.end - x.start), 0) / w.length : 0);
  const dl = mean(stance.left.windows);
  const dr = mean(stance.right.windows);
  const asym = dl && dr ? Math.round((Math.abs(dl - dr) / ((dl + dr) / 2)) * 100) : null;
  return {
    speed: +(travel / seconds).toFixed(2),
    cadence,
    step: +step.toFixed(2),
    asym,
    seconds,
    contacts: windows.map((w) => w.start)
  };
}

export { rigNameFor, readRootPosition };
